#pragma once

#include <Windows.h>
#include <stdint.h>
#include <Windows.h>
#include <psapi.h>
#include <d3d11.h>
#include <string>
#include <codecvt>
#include <locale>
#include <cstdint>
#include <algorithm>
#include <random>
#include <iostream>
#include <iomanip>
#include <emmintrin.h>
#include <comdef.h>
#include <iostream>
#include <filesystem>
#include <vector>
#include <fstream>
#include <d3d11.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <float.h>
#include <signal.h>
#include <sstream>
#include <stdio.h>
#include <lmcons.h>
#include <thread>
#include <map>
#include <shlobj.h>
#include <variant>
#include "detours/detours.h"
#pragma comment(lib, "Shell32.lib")
#pragma comment(lib, "Winmm.lib")
#pragma comment(lib,"d3d11.lib")
#pragma comment(lib, "detours/detours.lib")
#include "imgui/imgui.h"
#include "ImGui/imgui_impl_win32.h"
#include "ImGui/imgui_impl_dx11.h"
#include "ImGui/imgui_internal.h"
#include "ImGui/imgui_elements.h"
#include "core/sdk/utils/xorstr.hpp"
#include "core/sdk/utils/xorf.hpp"
#include "core/sdk/vector.hpp"
#include "core/sdk/utils/StringConverter.h"
#include "core/stdafx.hpp"
#include "core/drawing/D2DRender/ActualRender.hpp"
#include "Globals.hpp"
#include "Config/Menuvars.h"
#include "Config/NebelConfigSystem.h"
#include "core/drawing/D2DRender/Render.hpp"
#include "core/drawing/ui.hpp"
#include "core/sdk/utils/hookengine.hpp"
#include "core/sdk/mem.hpp"
#include "core/sdk/utils/crc32.hpp"
#include "core/sdk/il2cpp/wrapper.hpp"
#include "core/sdk/il2cpp/dissector.hpp"
#include "core/sdk/structs.hpp"
#include "core/sdk/game.hpp"
#include "core/main/cache.hpp"
#include "core/main/other.hpp"
#include "core/sdk/utils/math.hpp"
#include "core/main/entities.hpp"
#include "core/drawing/d3d.hpp"
#include "core/main/aimutils.hpp"

#include "Minhook/include/MinHook.h"
#include "core/main/hooks.hpp"
